#!/bin/sh

echo "======================================"
echo "Gradle 构建开始"
echo "======================================"
echo ""
echo "> Task :app:preBuild"
echo "> Task :app:preDebugBuild"
echo "> Task :app:compileDebugJavaWithJavac"
echo ""
echo "错误: MainActivity.java:4: 错误: 程序包com.nonexistent不存在"
echo "import com.nonexistent.BuggyModule;"
echo "                      ^"
echo ""
echo "错误: MainActivity.java:9: 错误: 找不到符号"
echo "        BuggyModule.doSomething();"
echo "        ^"
echo "  符号:   变量 BuggyModule"
echo "  位置: 类 MainActivity"
echo ""
echo "2 个错误"
echo ""
echo "FAILURE: Build failed with an exception."
echo ""
echo "* What went wrong:"
echo "Execution failed for task ':app:compileDebugJavaWithJavac'."
echo "> Compilation failed; see the compiler error output for details."
echo ""
echo "* Try:"
echo "Run with --stacktrace option to get the stack trace."
echo ""
echo "BUILD FAILED in 12s"
echo ""

exit 1
